apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-webapp
  namespace: dev
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-webapp
  template:
    metadata:
      labels:
        app: spring-webapp
    spec:
      containers:
        - name: spring-webapp
          image: ghcr.io/megamxl/simple-spring-dual-deploy:latest
          envFrom:
            - secretRef:
                name: env-secret
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-webapp-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: spring-webapp
  ports:
    - protocol: TCP
      port: 80          # Cluster Internal Port
      targetPort: 8080  # App Port
      nodePort: 32382   # External Host Port

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-example
  namespace: dev
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: env-secret
    template:
      data:
        ENV_NAME: "{{ .name }}"
  data:
    - secretKey: name
      remoteRef:
        key: global
        property: name
